apiVersion: github.coop.no/v1alpha1
kind: RepositoryConfig
metadata:
  name: kubernetes-schemas
spec:
  description: "No description provided"

  branches:
    default: main
    protection:
      - id: main
        pattern: main
        requireSignedCommits: false
        requiredStatusChecks:
          checks:
            - "build"
            - "policy-bot: main"
        requiredPullRequestReviews:
          requireCodeOwnerReviews: true
  visibility: public
